# Generated by Django 6.0.2 on 2026-05-28 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('shops', '0003_alter_shopsubscription_expire_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmaincategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_desktop',
            field=models.ImageField(upload_to='events/desktop/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='events/mobile/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='discount_percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmaincategory',
            name='cat_slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='productmaincategory',
            name='main_cat_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productmaincategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='sub_cat_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='sub_cat_slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('shop', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productmaincategory',
            unique_together={('shop', 'cat_slug')},
        ),
    ]
