# Generated by Django 6.0.2 on 2026-05-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerprofile_updated_at_and_more'),
        ('products', '0003_alter_productmaincategory_unique_together_and_more'),
        ('shops', '0004_couponactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('main_cat', 'Main Category'), ('sub_cat', 'Sub Category'), ('product', 'Product Base Matrix')], db_index=True, max_length=15)),
                ('item_name', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('add', 'Created'), ('edit', 'Updated/Mutated'), ('delete', 'Deleted/Purged')], db_index=True, max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shopownerprofile')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_activity_logs', to='shops.shop')),
            ],
            options={
                'db_table': 'inventory_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
