# Generated by Django 6.0.2 on 2026-05-22 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_shopownerprofile_shop_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Professional')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_limit', models.IntegerField(default=50)),
                ('order_limit', models.IntegerField(default=100)),
                ('duration_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_percentage', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopownerprofile')),
            ],
            options={
                'db_table': 'shop_coupons',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('shop_slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('invoice_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('shop_address', models.TextField()),
                ('trade_license', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('theme_color', models.CharField(default='#000000', max_length=20)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='shops/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='accounts.shopownerprofile')),
            ],
            options={
                'verbose_name': 'Shop',
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='ShopActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='shops.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='shop_media/')),
                ('media_type', models.CharField(default='Banner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopownerprofile')),
            ],
            options={
                'db_table': 'shop_media',
            },
        ),
        migrations.CreateModel(
            name='ShopSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('profile_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.shopownerprofile')),
            ],
            options={
                'db_table': 'shop_social_media',
            },
        ),
        migrations.CreateModel(
            name='ShopSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_subscription', to='shops.shop')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.subscriptionplan')),
            ],
            options={
                'db_table': 'shop_subscriptions',
            },
        ),
    ]
