# Generated by Django 6.0.2 on 2026-05-27 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='shopmedia',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='shopsocialmedia',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_coupons', to='shops.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopmedia',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shop_media', to='shops.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsocialmedia',
            name='shop',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='shops.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
