# Generated by Django 6.0.2 on 2026-05-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_coupon_admin_user_remove_shopmedia_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsubscription',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
