# Generated by Django 6.0.2 on 2026-05-30 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerprofile_updated_at_and_more'),
        ('shops', '0003_alter_shopsubscription_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Edited'), ('DELETE', 'Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_activities', to='shops.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.shopownerprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
