# Generated by Django 6.0.2 on 2026-06-02 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_inventoryactivitylog'),
        ('shops', '0004_couponactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('banner_desktop', models.ImageField(upload_to='events/desktop/')),
                ('banner_mobile', models.ImageField(blank=True, null=True, upload_to='events/mobile/')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired')], db_index=True, default='draft', max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(blank=True, related_name='shop_app_products_events', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_app_events', to='shops.shop')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title_backup', models.CharField(help_text='Event ডিলিট হয়ে গেলেও যেন নাম ট্র্যাক করা যায়', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('activate', 'Activated'), ('deactivate', 'Deactivated')], max_length=20)),
                ('changes_logged', models.TextField(blank=True, help_text='কী কী চেঞ্জ হয়েছে তার ডিটেইলস (ঐচ্ছিক)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='shops.events')),
            ],
            options={
                'verbose_name_plural': 'Event Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='unique_shop_event_slug'),
        ),
    ]
