# Generated by Django 6.0.2 on 2026-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_events_eventactivity_events_unique_shop_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
