# Generated by Django 6.0.2 on 2026-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
