# Generated by Django 6.0.2 on 2026-06-11 04:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerprofile_updated_at_and_more'),
        ('shops', '0009_shopnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating must be between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Write your review here (max 500 characters)', max_length=500, null=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='Is Visible on Site')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='accounts.customerprofile', verbose_name='Reviewer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.shop', verbose_name='Target Shop')),
            ],
            options={
                'verbose_name': 'Shop Review',
                'verbose_name_plural': 'Shop Reviews',
                'db_table': 'shop_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('shop', 'customer')},
            },
        ),
    ]
