# Generated by Django 6.0.2 on 2026-05-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopownerprofile',
            name='shop_description',
        ),
        migrations.RemoveField(
            model_name='shopownerprofile',
            name='shop_logo',
        ),
        migrations.RemoveField(
            model_name='shopownerprofile',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='shopownerprofile',
            name='shop_slug',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='shopownerprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='shopownerprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='shopownerprofile',
            name='nid_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopownerprofile',
            name='trade_license',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
