# Generated by Django 6.0.2 on 2026-05-22 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shopownerprofile_shop_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shopownerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_shop_owner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
